/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/devroom.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/devroom.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh name="ComputerStand" geometry={nodes.ComputerStand.geometry} material={materials['Material.005']} position={[-3.325, 2.701, -3.198]} rotation={[0, -0.718, 0]} />
      <group name="Desk" position={[-0.021, 0.76, -2.546]}>
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.001']} />
        <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['Material.002']} />
        <mesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials['Material.003']} />
      </group>
      <group name="Keyboard" position={[-2.447, 2.771, -2.466]} rotation={[0.072, 0.896, -0.057]}>
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials['Metal.007']} />
        <mesh name="Plane015_1" geometry={nodes.Plane015_1.geometry} material={materials['Black.004']} />
        <mesh name="Plane015_2" geometry={nodes.Plane015_2.geometry} material={materials['White.011']} />
      </group>
      <mesh name="PC" geometry={nodes.PC.geometry} material={materials.UnderneathDesk} position={[-2.989, 0.763, -2.985]} rotation={[0, -1.545, 0]} />
      <mesh name="BedFrame" geometry={nodes.BedFrame.geometry} material={materials.BedColour} position={[2.445, 1.056, 1.675]} />
      <mesh name="Mattress" geometry={nodes.Mattress.geometry} material={materials['Material.004']} position={[2.464, 1.508, 1.639]} />
      <mesh name="Blanket" geometry={nodes.Blanket.geometry} material={materials['Material.006']} position={[2.618, 1.631, 1.181]} />
      <mesh name="Pillow1" geometry={nodes.Pillow1.geometry} material={materials['Material.003']} position={[-1.151, 0.675, -0.018]} />
      <mesh name="Pillow2" geometry={nodes.Pillow2.geometry} material={materials['Material.003']} position={[-2.46, 0.668, 0.003]} />
      <mesh name="WallShelf" geometry={nodes.WallShelf.geometry} material={materials['lambert3SG.001']} position={[0.41, 4.133, -3.778]} />
      <mesh name="BlueBookSmallShelf" geometry={nodes.BlueBookSmallShelf.geometry} material={materials.Book1} position={[-0.194, 4.769, -3.725]} rotation={[-Math.PI, 1.55, -Math.PI]} />
      <mesh name="OrangeBookSmallShelf" geometry={nodes.OrangeBookSmallShelf.geometry} material={materials.Book2} position={[-0.004, 4.769, -3.725]} rotation={[-Math.PI, 1.55, -Math.PI]} />
      <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials.MetallicBall} position={[1.072, 4.452, -3.771]} />
      <group name="Chair" position={[-1.175, 0.663, -1.153]} rotation={[0, 0.809, 0]}>
        <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials.Office_Cha} />
        <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials.Office_Cha_1} />
      </group>
      <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials.WhiteSphere} position={[0.553, 4.433, -3.721]} />
      <mesh name="Mouse" geometry={nodes.Mouse.geometry} material={materials.Mouse} position={[-0.924, 2.728, -2.998]} rotation={[Math.PI, -1.061, Math.PI]} />
      <mesh name="BookShelf" geometry={nodes.BookShelf.geometry} material={materials.BookShelf} position={[-3.357, 1.155, 3.015]} />
      <group name="MidBookonDesk" position={[-2.965, 2.846, 0.656]} rotation={[Math.PI, -1.563, Math.PI]}>
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['White.002']} />
        <mesh name="Plane013_1" geometry={nodes.Plane013_1.geometry} material={materials['Book.002']} />
      </group>
      <group name="TopBookonDesk" position={[-3.058, 2.967, 0.635]} rotation={[Math.PI, -1.563, Math.PI]}>
        <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials['White.003']} />
        <mesh name="Plane017_1" geometry={nodes.Plane017_1.geometry} material={materials['Book.003']} />
      </group>
      <group name="BottomBookonDesk" position={[-2.907, 2.714, 0.658]} rotation={[Math.PI, -1.556, Math.PI]}>
        <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials['White.004']} />
        <mesh name="Plane018_1" geometry={nodes.Plane018_1.geometry} material={materials['Book.004']} />
      </group>
      <group name="BlueBookShelf" position={[-3.156, 4.912, 3.741]} rotation={[1.564, 0.067, -0.009]}>
        <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials['White.005']} />
        <mesh name="Plane019_1" geometry={nodes.Plane019_1.geometry} material={materials['Book.005']} />
      </group>
      <group name="RedBookShelf" position={[-3.156, 4.912, 3.611]} rotation={[1.564, 0.067, -0.009]}>
        <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={materials['White.007']} />
        <mesh name="Plane021_1" geometry={nodes.Plane021_1.geometry} material={materials['Book.007']} />
      </group>
      <group name="GreenBookShelf" position={[-3.156, 4.912, 3.48]} rotation={[1.564, 0.067, -0.009]}>
        <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials['White.008']} />
        <mesh name="Plane022_1" geometry={nodes.Plane022_1.geometry} material={materials['Book.008']} />
      </group>
      <mesh name="BookShelfOrangeBook" geometry={nodes.BookShelfOrangeBook.geometry} material={materials.OrangeBookonShelf} position={[-3.172, 4.83, 3.403]} rotation={[Math.PI, -0.002, Math.PI]} />
      <mesh name="WhiteBookonShelf" geometry={nodes.WhiteBookonShelf.geometry} material={materials.WhiteBookonShelf} position={[-3.172, 4.83, 3.252]} rotation={[Math.PI, -0.002, Math.PI]} />
      <mesh name="YellowBookonShelf" geometry={nodes.YellowBookonShelf.geometry} material={materials.YellowBookonShelf} position={[-3.172, 4.83, 3.104]} rotation={[Math.PI, -0.002, Math.PI]} />
      <mesh name="LightGreenBook" geometry={nodes.LightGreenBook.geometry} material={materials['Book2.005']} position={[-3.172, 4.775, 2.866]} rotation={[Math.PI, -0.002, Math.PI]} />
      <mesh name="PurpleBookonShelf" geometry={nodes.PurpleBookonShelf.geometry} material={materials.PinkBookonShelf} position={[-3.172, 4.775, 2.975]} rotation={[Math.PI, -0.002, Math.PI]} />
      <group name="BlackBookShelf001" position={[-3.156, 4.123, 2.443]} rotation={[1.564, 0.067, -0.009]}>
        <mesh name="Plane024" geometry={nodes.Plane024.geometry} material={materials['White.009']} />
        <mesh name="Plane024_1" geometry={nodes.Plane024_1.geometry} material={materials['Book.009']} />
      </group>
      <group name="BlackBookShelf002" position={[-3.156, 4.123, 2.573]} rotation={[1.564, 0.067, -0.009]}>
        <mesh name="Plane025" geometry={nodes.Plane025.geometry} material={materials['White.010']} />
        <mesh name="Plane025_1" geometry={nodes.Plane025_1.geometry} material={materials['Book.010']} />
      </group>
      <group name="BlackBookShelf003" position={[-3.156, 4.123, 2.7]} rotation={[1.564, 0.067, -0.009]}>
        <mesh name="Plane026" geometry={nodes.Plane026.geometry} material={materials['White.011']} />
        <mesh name="Plane026_1" geometry={nodes.Plane026_1.geometry} material={materials['Book.011']} />
      </group>
      <group name="BlackBookShelf004" position={[-3.156, 4.123, 2.315]} rotation={[1.564, 0.067, -0.009]}>
        <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials['White.012']} />
        <mesh name="Plane027_1" geometry={nodes.Plane027_1.geometry} material={materials['Book.012']} />
      </group>
      <group name="BlackBookShelf" position={[-3.156, 4.123, 2.183]} rotation={[1.564, 0.067, -0.009]}>
        <mesh name="Plane028" geometry={nodes.Plane028.geometry} material={materials['White.013']} />
        <mesh name="Plane028_1" geometry={nodes.Plane028_1.geometry} material={materials['Book.013']} />
      </group>
      <group name="SmallTree" position={[-3.106, 4.04, 3.604]}>
        <mesh name="mesh31856083001" geometry={nodes.mesh31856083001.geometry} material={materials['mat9.001']} />
        <mesh name="mesh31856083001_1" geometry={nodes.mesh31856083001_1.geometry} material={materials['mat21.001']} />
        <mesh name="mesh31856083001_2" geometry={nodes.mesh31856083001_2.geometry} material={materials['mat20.001']} />
      </group>
      <group name="BigTree" position={[2.914, 1.885, -3.339]}>
        <mesh name="mesh24448074" geometry={nodes.mesh24448074.geometry} material={materials.TreeLeaves} />
        <mesh name="mesh24448074_1" geometry={nodes.mesh24448074_1.geometry} material={materials.TreePot} />
        <mesh name="mesh24448074_2" geometry={nodes.mesh24448074_2.geometry} material={materials.TreeGround} />
        <mesh name="mesh24448074_3" geometry={nodes.mesh24448074_3.geometry} material={materials['mat9.001']} />
      </group>
      <group name="Screen" position={[-3.105, 4.042, -2.885]} rotation={[0.022, -0.676, -0.037]}>
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.metal} />
        <mesh name="Plane002_1" geometry={nodes.Plane002_1.geometry} material={materials.screen} />
      </group>
      <group name="EntireRoom" position={[0, 0.774, 0]}>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Walls} />
        <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.Floor} />
      </group>
    </group>
  )
}

useGLTF.preload('/devroom.gltf')
