/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Office_Scene.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture, useVideoTexture } from '@react-three/drei'
import * as THREE from "three";

export function Office(props) {
    const { nodes, materials } = useGLTF('models/Office_Scene_Mac_Test.gltf');
    const texture = useTexture("textures/BakedTestCurr.jpg");
    const textureMac = useTexture("textures/Mac.jpg");
    const textureVSCode = useVideoTexture("textures/vscode6.mp4");

    texture.flipY = false;
    texture.encoding = THREE.sRGBEncoding;
    textureMac.flipY = false;
    textureMac.encoding = THREE.sRGBEncoding;

    // textureVSCode.flipY = false;
    // textureVSCode.rotation = 1;

    const textureMaterial= new THREE.MeshStandardMaterial({
        map: texture,
    });

    const textureMacMaterial= new THREE.MeshStandardMaterial({
        map: textureMac,
    });
    
    return (
        <group {...props} dispose={null}>
        <group name="Desk" position={[-0.021, 0.76, -2.286]}>
          <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={textureMaterial} />
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={textureMaterial} />
          <mesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={textureMaterial} />
        </group>
        <group name="Keyboard" position={[-2.447, 2.771, -2.466]} rotation={[0.072, 0.896, -0.057]} scale={0.795}>
          <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={textureMaterial} />
          <mesh name="Plane015_1" geometry={nodes.Plane015_1.geometry} material={textureMaterial} />
          <mesh name="Plane015_2" geometry={nodes.Plane015_2.geometry} material={textureMaterial} />
        </group>
        <mesh name="PC" geometry={nodes.PC.geometry} material={textureMaterial} position={[-2.989, 0.763, -2.985]} rotation={[0, -1.545, 0]} />
        <mesh name="WallShelf" geometry={nodes.WallShelf.geometry} material={textureMaterial} position={[0.41, 4.133, -3.778]} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={textureMaterial} position={[0.953, 4.48, -3.609]} />
        <group name="Chair" position={[-1.175, 0.663, -1.153]} rotation={[0, 0.809, 0]} scale={0.954}>
          <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={textureMaterial} />
          <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={textureMaterial} />
        </group>
        <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={textureMaterial} position={[0.37, 4.476, -3.47]} />
        <mesh name="Mouse" geometry={nodes.Mouse.geometry} material={textureMaterial} position={[-1.107, 2.721, -2.733]} rotation={[Math.PI, -0.894, Math.PI]} />
        <mesh name="BookShelf" geometry={nodes.BookShelf.geometry} material={textureMaterial} position={[-3.357, 1.155, 3.107]} />
        <group name="MidBookonDesk" position={[-2.965, 2.846, 0.656]} rotation={[Math.PI, -1.563, Math.PI]}>
          <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={textureMaterial} />
          <mesh name="Plane013_1" geometry={nodes.Plane013_1.geometry} material={textureMaterial} />
        </group>
        <group name="TopBookonDesk" position={[-3.058, 2.967, 0.635]} rotation={[Math.PI, -1.563, Math.PI]}>
          <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={textureMaterial} />
          <mesh name="Plane017_1" geometry={nodes.Plane017_1.geometry} material={textureMaterial} />
        </group>
        <group name="BottomBookonDesk" position={[-2.907, 2.714, 0.658]} rotation={[Math.PI, -1.556, Math.PI]}>
          <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={textureMaterial} />
          <mesh name="Plane018_1" geometry={nodes.Plane018_1.geometry} material={textureMaterial} />
        </group>
        <group name="BlueBookShelf" position={[-3.156, 4.912, 3.741]} rotation={[1.564, 0.067, -0.009]}>
          <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={textureMaterial} />
          <mesh name="Plane019_1" geometry={nodes.Plane019_1.geometry} material={textureMaterial} />
        </group>
        <group name="RedBookShelf" position={[-3.156, 4.912, 3.611]} rotation={[1.564, 0.067, -0.009]}>
          <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={textureMaterial} />
          <mesh name="Plane021_1" geometry={nodes.Plane021_1.geometry} material={textureMaterial} />
        </group>
        <group name="GreenBookShelf" position={[-3.156, 4.912, 3.48]} rotation={[1.564, 0.067, -0.009]}>
          <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={textureMaterial} />
          <mesh name="Plane022_1" geometry={nodes.Plane022_1.geometry} material={textureMaterial} />
        </group>
        <group name="BlackBookShelf001" position={[-3.156, 4.123, 2.443]} rotation={[1.564, 0.067, -0.009]}>
          <mesh name="Plane024" geometry={nodes.Plane024.geometry} material={textureMaterial} />
          <mesh name="Plane024_1" geometry={nodes.Plane024_1.geometry} material={textureMaterial} />
        </group>
        <group name="BlackBookShelf004" position={[-3.156, 4.123, 2.315]} rotation={[1.564, 0.067, -0.009]}>
          <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={textureMaterial} />
          <mesh name="Plane027_1" geometry={nodes.Plane027_1.geometry} material={textureMaterial} />
        </group>
        <group name="BlackBookShelf" position={[-3.156, 4.123, 2.183]} rotation={[1.564, 0.067, -0.009]}>
          <mesh name="Plane028" geometry={nodes.Plane028.geometry} material={textureMaterial} />
          <mesh name="Plane028_1" geometry={nodes.Plane028_1.geometry} material={textureMaterial} />
        </group>
        <group name="SmallTree" position={[-3.106, 4.04, 3.604]}>
          <mesh name="mesh31856083001" geometry={nodes.mesh31856083001.geometry} material={textureMaterial} />
          <mesh name="mesh31856083001_1" geometry={nodes.mesh31856083001_1.geometry} material={textureMaterial} />
          <mesh name="mesh31856083001_2" geometry={nodes.mesh31856083001_2.geometry} material={textureMaterial} />
        </group>
        <group name="BigTree" position={[2.914, 1.885, -3.339]}>
          <mesh name="mesh24448074" geometry={nodes.mesh24448074.geometry} material={textureMaterial} />
          <mesh name="mesh24448074_1" geometry={nodes.mesh24448074_1.geometry} material={textureMaterial} />
          <mesh name="mesh24448074_2" geometry={nodes.mesh24448074_2.geometry} material={textureMaterial} />
          <mesh name="mesh24448074_3" geometry={nodes.mesh24448074_3.geometry} material={textureMaterial} />
        </group>
        <mesh name="Carpet" geometry={nodes.Carpet.geometry} material={materials.Carpet} position={[1.133, 0.824, 1.077]} rotation={[0, 0.909, 0]} />
        <group name="iMac" position={[-2.903, 2.78, -2.934]} rotation={[0, -0.697, 0]} scale={3.93}>
          <mesh name="iMac_1" geometry={nodes.iMac_1.geometry} material={textureMacMaterial} />
          <mesh name="iMac_1_1" geometry={nodes.iMac_1_1.geometry} material={textureMacMaterial} />
        </group>
        <mesh 
            name="iMac001" 
            geometry={nodes.iMac001.geometry}  
            position={[-2.903, 2.78, -2.934]} 
            rotation={[0, -0.697, 0]} scale={3.93} 
        >
            <meshBasicMaterial map={textureVSCode} toneMapped={false} />
        </mesh>
        <group name="EntireRoom" position={[0, 0.774, 0]} scale={1.051}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={textureMaterial} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={textureMaterial} />
        </group>
      </group>
    )
}

useGLTF.preload('models/Office_Scene_Mac_Test.gltf')
